# -*- coding: utf-8 -*-
"""HousePrediction1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hlpf3w7D00mGHdRsVqavMAX3aFhOvKN5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn import datasets
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.datasets import fetch_california_housing
housing=fetch_california_housing()

housing_df=pd.DataFrame(data=housing.data, columns=housing.feature_names)
housing_df['HousePrice'] = housing.target
housing_df.head()

housing_df.describe()

housing_df.isna().sum()

sns.pairplot(housing_df,height=3)
plt.suptitle('PairPlot of features against housing price',y=0.12)
plt.show()

housing_df.plot(
    kind="scatter",
    x="Longitude",
    y="Latitude",
    alpha=0.4,
    s=housing_df['Population']/100,
    label = "Population",
    c="HousePrice",
    cmap="jet",
    colorbar=True,
    figsize=(10,8)
)
plt.show()

corr = housing_df.corr()
plt.figure(figsize=(10,8))
sns.heatmap(corr,annot=True,cmap='coolwarm', fmt=".2f", linewidth=0.5)

corr["HousePrice"].abs().sort_values(ascending=False)

#relationship between medical insurance and houseprice from housing dataframe
medinc=housing_df['MedInc']
houseprice = housing_df['HousePrice']
plt.figure(figsize=(8,6))
plt.scatter(medinc,houseprice,alpha=0.5,color='blue')
plt.title('Scatter plot of MedInc vs HousePrice')
plt.xlabel('MedInc')
plt.ylabel('HousePrice')
plt.grid(True)
plt.show()

from statsmodels.stats.outliers_influence import variance_inflation_factor
housing_df_vif=housing_df.drop('HousePrice',axis=1)
housing_df_vif=housing_df_vif.apply(pd.to_numeric,errors='coerce')
vif_data=pd.DataFrame()
vif_data["Feature"] = housing_df_vif.columns
vif_data["VIF"]  =  [variance_inflation_factor(housing_df_vif.values, i) for i in range(len(housing_df_vif.columns))]
print(vif_data)

housing_df= housing_df.drop(['Latitude','Longitude'],axis=1)

cols_to_convert = ['MedInc','HouseAge','AveRooms','Population','AveOccup']
housing_df[cols_to_convert]  = housing_df[cols_to_convert].apply(pd.to_numeric,errors='coerce')
housing_df['HousePrice']= pd.to_numeric(housing_df['HousePrice'],errors='coerce')
x=sm.add_constant(housing_df.drop('HousePrice',axis=1))
y=housing_df['HousePrice']
model=sm.OLS(y,x).fit()

residuals=model.resid
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
sns.histplot(residuals,kde=True)
plt.title('Residuals distribution')
plt.subplot(1,2,2)
plt.scatter(model.predict(x),residuals)
plt.axhline(y=0, color='red', linestyle='--')
plt.title('Residuals vs Predicted')
plt.ylabel('Residuals')
plt.show()
print("Model coefficient:\n",model.params)

from sklearn.metrics import mean_squared_error, r2_score
predictions=model.predict(x)
print("R Square Score:",r2_score(y,predictions))
print("MSE:",mean_squared_error(y,predictions))

import matplotlib.pyplot as plt
def plot_boxplots(df):
     fig,axes=plt.subplots(1, len(df.columns), figsize=(20,5))
     for i,column_name in enumerate(df.columns):
            df.boxplot(column=column_name,ax=axes[i])
     plt.show()
plot_boxplots(housing_df)

def remove_outliers(df):
    df_no_outliers = df.copy()
    for column_name in df.columns:
        Q1 = df[column_name].quantile(0.25)
        Q3 = df[column_name].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df_no_outliers[column_name] = df_no_outliers[column_name].apply(
            lambda x: lower_bound if x < lower_bound
                      else upper_bound if x > upper_bound
                      else x
        )
    return df_no_outliers

housing_df_new = remove_outliers(housing_df)

plot_boxplots(housing_df_new)

cols_to_convert=['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','HousePrice']
housing_df_new[cols_to_convert]=housing_df_new[cols_to_convert].apply(pd.to_numeric,errors='coerce')
housing_df_new['HousePrice'] = pd.to_numeric(housing_df_new['HousePrice'], errors='coerce')
x=sm.add_constant(housing_df_new.drop('HousePrice',axis=1))
y=housing_df_new['HousePrice']
model =sm.OLS(y,x).fit()

residuals=model.resid
plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
sns.histplot(residuals,kde=True)
plt.title('Residuals distribution')
plt.subplot(1,2,2)
plt.scatter(model.predict(x),residuals)
plt.axhline(y=0,color='red',linestyle='--')
plt.title('Residuals vs Predicted')
plt.xlabel('Predicted values')
plt.ylabel('Residuals')
plt.show()
print("Model coefficient:\n", model.params)

from sklearn.metrics import mean_squared_error,r2_score
predictions=model.predict(x)
print("R square score:",r2_score(y,predictions))
print("MSE:",mean_squared_error(y,predictions))

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

X_train_const = sm.add_constant(X_train)
X_test_const = sm.add_constant(X_test)

model_final = sm.OLS(y_train, X_train_const).fit()

y_pred_final = model_final.predict(X_test_const)

from sklearn.metrics import mean_squared_error, mean_absolute_error
r2 = r2_score(y_test, y_pred_final)
mse = mean_squared_error(y_test, y_pred_final)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred_final)

print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")